# Site settings
title: Polygonal Tree Blog
email: luis.garcia@polygonaltree.co.uk
description: > # this means to ignore newlines until "baseurl:"
  Blog and project collaboration site.
baseurl: "/" # the subpath of your site, e.g. /blog/
url: "http://polygonaltee.science" # the base hostname & protocol for your site
twitter_username: PolygonalTree
github_username:  Polygonaltree

# Build settings
markdown: kramdown
